/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const NoteId = IDL.Nat;
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'body' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : IDL.Int,
});

export const idlService = IDL.Service({
  'createNote' : IDL.Func([NoteInput], [Note], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
  'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
  'updateNote' : IDL.Func([NoteId, NoteInput], [Note], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const NoteId = IDL.Nat;
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'body' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : IDL.Int,
  });
  
  return IDL.Service({
    'createNote' : IDL.Func([NoteInput], [Note], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'getNote' : IDL.Func([NoteId], [IDL.Opt(Note)], ['query']),
    'listNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'searchNotes' : IDL.Func([IDL.Text], [IDL.Vec(Note)], ['query']),
    'updateNote' : IDL.Func([NoteId, NoteInput], [Note], []),
  });
};

export const init = ({ IDL }) => { return []; };