/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Note {
  'id' : NoteId,
  'title' : string,
  'owner' : Principal,
  'body' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'updatedAt' : bigint,
}
export type NoteId = bigint;
export interface NoteInput {
  'title' : string,
  'body' : string,
  'tags' : Array<string>,
}
export interface _SERVICE {
  'createNote' : ActorMethod<[NoteInput], Note>,
  'deleteNote' : ActorMethod<[NoteId], undefined>,
  'getNote' : ActorMethod<[NoteId], [] | [Note]>,
  'listNotes' : ActorMethod<[], Array<Note>>,
  'searchNotes' : ActorMethod<[string], Array<Note>>,
  'updateNote' : ActorMethod<[NoteId, NoteInput], Note>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];